// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ8gvzJwCQbK_AS-kzZ5E9VTu-6dzdryk',
    appId: '1:804404038436:web:97510c230b25f4fc3381b1',
    messagingSenderId: '804404038436',
    projectId: 'taklees-eefd6',
    authDomain: 'taklees-eefd6.firebaseapp.com',
    storageBucket: 'taklees-eefd6.appspot.com',
    measurementId: 'G-H7K9933BM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5e-nPuhiyIkrZDEr8Sf5MVeJwoctiwmo',
    appId: '1:804404038436:android:93fb7b9efc6ea1e93381b1',
    messagingSenderId: '804404038436',
    projectId: 'taklees-eefd6',
    storageBucket: 'taklees-eefd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYzJ11GzGWXTs5H8LdVnDbhqccAAeJpZA',
    appId: '1:804404038436:ios:5964b25505adbffc3381b1',
    messagingSenderId: '804404038436',
    projectId: 'taklees-eefd6',
    storageBucket: 'taklees-eefd6.appspot.com',
    iosBundleId: 'com.example.safeerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYzJ11GzGWXTs5H8LdVnDbhqccAAeJpZA',
    appId: '1:804404038436:ios:c293b7b5e9d065063381b1',
    messagingSenderId: '804404038436',
    projectId: 'taklees-eefd6',
    storageBucket: 'taklees-eefd6.appspot.com',
    iosBundleId: 'com.example.safeerApp.RunnerTests',
  );
}
